version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    security-updates: true

  # Monitor GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflows
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 0
    security-updates: true
